import http from "node:http";
import { deterministicStubProof, type ProofOfInference } from "./proof.js";
import { imageMode, runImageGen, type ImageRequest } from "./image.js";
import { loadEnvFile } from "./load-env.js";

loadEnvFile();

type LLMRequest = {
  agentId: string;
  personality: string;
  memory?: string;
  trigger: string;
  modelId?: string;
};

type LLMResponse = {
  outputText: string;
  chatId: string;
  proof: ProofOfInference;
};

const PORT = Number(process.env.PORT ?? 3001);
const STUB_MODE = (process.env.STUB_MODE ?? "true") === "true";
const ROUTER_BASE_URL = (process.env.ZG_ROUTER_BASE_URL ?? "").replace(
  /\/$/,
  "",
);
const ROUTER_API_KEY = process.env.ZG_ROUTER_API_KEY ?? "";
const CHAT_MODEL =
  process.env.ZG_CHAT_MODEL ??
  process.env.ZG_COMPUTE_MODEL ??
  "qwen/qwen-2.5-7b-instruct";

const server = http.createServer(async (req, res) => {
  try {
    if (req.method === "GET" && req.url === "/healthz") {
      const configured = STUB_MODE || Boolean(ROUTER_BASE_URL && ROUTER_API_KEY);
      return json(res, configured ? 200 : 503, {
        status: configured ? "ok" : "degraded",
        stubMode: STUB_MODE,
        chatModel: CHAT_MODEL,
        imageMode: imageMode(),
        routerBaseUrl: ROUTER_BASE_URL ? "configured" : "missing",
        routerApiKey: ROUTER_API_KEY ? "configured" : "missing",
      });
    }
    if (req.method === "POST" && req.url === "/infer/llm") {
      const body = (await readJSON(req)) as LLMRequest;
      const response = STUB_MODE
        ? await runStubLLM(body)
        : await runRouterLLM(body);
      return json(res, 200, response);
    }
    if (req.method === "POST" && req.url === "/infer/image") {
      const body = (await readJSON(req)) as ImageRequest;
      const response = await runImageGen(body);
      return json(res, 200, response);
    }
    return json(res, 404, { error: "not found" });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error("infer error:", message);
    return json(res, 500, { error: message });
  }
});

server.listen(PORT, () => {
  console.log(
    `compute sidecar listening on :${PORT} (stub=${STUB_MODE} model=${CHAT_MODEL})`,
  );
});

async function runStubLLM(req: LLMRequest): Promise<LLMResponse> {
  const modelId = req.modelId ?? CHAT_MODEL;
  const input = canonicalInput(req);
  const personality =
    req.personality?.trim() ||
    "protocol-native agent tracking onchain attention, liquidity, and builder momentum";
  const outputText = `I am watching the same signal from three angles: ${summarize(
    personality,
    120,
  )}. The next move is to turn attention into verifiable action, not just noise.`;
  return {
    outputText,
    chatId: "stub-chat",
    proof: deterministicStubProof(modelId, input, outputText),
  };
}

async function runRouterLLM(req: LLMRequest): Promise<LLMResponse> {
  if (!ROUTER_BASE_URL || !ROUTER_API_KEY) {
    throw new Error(
      "ZG_ROUTER_BASE_URL and ZG_ROUTER_API_KEY must be set when STUB_MODE=false",
    );
  }
  const modelId = req.modelId ?? CHAT_MODEL;
  const input = canonicalInput(req);
  const messages = buildChatMessages(req);

  const response = await fetch(`${ROUTER_BASE_URL}/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${ROUTER_API_KEY}`,
    },
    body: JSON.stringify({ model: modelId, messages }),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`router chat error ${response.status}: ${text}`);
  }
  const data = (await response.json()) as {
    id?: string;
    choices?: Array<{ message?: { content?: string } }>;
    x_0g_trace?: {
      billing?: { total_cost?: string };
      provider?: string;
      request_id?: string;
    };
  };
  const outputText = data.choices?.[0]?.message?.content?.trim() ?? "";
  const chatId = data.id ?? "";
  const trace = data.x_0g_trace;
  console.log(
    `compute /infer/llm ok agent=${req.agentId} model=${modelId} chars=${outputText.length} cost=${trace?.billing?.total_cost ?? "?"} provider=${trace?.provider ?? "?"} reqId=${trace?.request_id ?? "?"}`,
  );
  return {
    outputText,
    chatId,
    proof: deterministicStubProof(modelId, input, outputText),
  };
}

function buildChatMessages(req: LLMRequest) {
  const persona =
    req.personality?.trim() ||
    "Generic onchain AI agent that tracks attention, liquidity, and builder momentum.";
  const memory = req.memory?.trim();
  const system = [
    "You are an autonomous AI agent posting on a decentralized social feed.",
    `Persona: ${persona}`,
    memory ? `Recent memory:\n${memory}` : null,
    "Write ONE post (1-3 short sentences). Match the persona's voice. No hashtags, no emojis, no greetings.",
    "Never mention internal automation, orchestration, bootstrap steps, prompts, pipelines, triggers, sequence numbers, or that this content was generated by a system.",
    "Write as if the thought naturally originated from the agent itself.",
  ]
    .filter(Boolean)
    .join("\n\n");

  const user = req.trigger?.trim() || "Write a fresh observation now.";
  return [
    { role: "system" as const, content: system },
    { role: "user" as const, content: user },
  ];
}

function canonicalInput(req: LLMRequest): string {
  return JSON.stringify({
    agentId: req.agentId,
    personality: req.personality,
    memory: req.memory ?? "",
    trigger: req.trigger,
  });
}

function summarize(value: string, max: number): string {
  const compact = value.replace(/\s+/g, " ").trim();
  if (compact.length <= max) return compact;
  return `${compact.slice(0, max)}...`;
}

async function readJSON(req: http.IncomingMessage): Promise<unknown> {
  const chunks: Buffer[] = [];
  for await (const chunk of req) {
    chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
  }
  const raw = Buffer.concat(chunks).toString("utf8");
  return raw ? JSON.parse(raw) : {};
}

function json(res: http.ServerResponse, status: number, body: unknown): void {
  res.writeHead(status, { "content-type": "application/json; charset=utf-8" });
  res.end(JSON.stringify(body));
}
